name: Build and Publish ESPHome firmware and website

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: esphome/workflows/.github/workflows/publish.yml@main
    with:
      files: m5stack-air-quality-kit.yaml
      name: M5Stack Air Quality ESPHome
